// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "swoosh":return img`
. . . . . d 1 1 1 1 . . . . . . 
. . . . . . d 1 1 1 1 . . . . . 
. . . . . . . d 1 1 1 1 . . . . 
. . . . . . . d 1 1 1 1 . . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . . d 1 1 1 1 . . . 
. . . . . . . d 1 1 1 1 . . . . 
. . . . . . . d 1 1 1 1 . . . . 
. . . . . . d 1 1 1 1 . . . . . 
. . . . . d 1 1 1 1 . . . . . . 
`;
            case "image2":
            case "Grendel Sprite":return img`
......e......e...........
.....eee.cc.eee..........
.....eeecccceee..........
.....eeecccccee..........
.....eeecccccee..........
....eeeeeeeeeeee.........
....eeeeeeeeeeeee........
....eeeee22ee22ee........
....eeeee22ee22ee........
....eeeeeeeeeeeeee.......
....eeeeeeeeeeeeeeee.....
.....eeeee3eeeeeeeee.....
.....eeeef3ff3f3eee......
......eeee3f3f3..........
.......eeeeeee...........
...eeeeeeeeeeeeee.....33.
..eeeeeeeeeeeeeeee...3...
.eeeeeeeeeeeeeeeeee.eee33
eeeeeeeeeeeeeeeeeeeeee3..
eeefeeeeeeeeeeeeeeeeeee..
eeeefeeeeeeeeeee.eeee....
eee33feeeeeeeeee.........
.eee33eeeeeeeeee.........
..eeefeeeeeeeeee.........
....333333333333.........
....ee333333333e.........
....eeee333.eeee.........
...eeeee..3eeeee.........
...eeeeee..eeeeee........
....eeeeee..eeeeee.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
